{{- if .Values.match.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: black-ice-match
  labels:
    {{- include "black-ice.componentLabels" (dict "component" "match" "Release" .Release) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: black-ice-match
  minReplicas: {{ .Values.match.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.match.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.match.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
