apiVersion: v1
kind: Secret
metadata:
  name: black-ice-secrets
  labels:
    {{- include "black-ice.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.connections.databaseUrl | quote }}
  BLACK_ICE_API_KEYS: {{ .Values.apiKeys | quote }}
